# Generated by Django 4.0.3 on 2022-03-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=100)),
                ('DateOfJoining', models.DateField(max_length=10)),
                ('PhotoFileName', models.CharField(max_length=10)),
            ],
        ),
    ]
